# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_type',
                 models.CharField(choices=[('searching', 'Searching'), ('offering', 'Offering')], max_length=20,
                                  verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('image',
                 models.ImageField(blank=True, max_length=255, upload_to='bulletin_board/', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Bulletins',
                'ordering': ('title',),
                'verbose_name': 'Bulletin',
            },
        ),
    ]
