# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 07:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('small_image', models.ImageField(upload_to='')),
                ('medium_image', models.ImageField(upload_to='')),
                ('large_image', models.ImageField(upload_to='')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
