# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='large_image',
            field=models.ImageField(upload_to=utils.models.upload_to),
        ),
        migrations.AlterField(
            model_name='location',
            name='medium_image',
            field=models.ImageField(upload_to=utils.models.upload_to),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='small_image',
            field=models.ImageField(upload_to=utils.models.upload_to),
        ),
    ]
