# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '\uf0e9'), (2, '\uf0e9\uf0e9'), (3, '\uf0e9\uf0e9\uf0e9'), (4, '\uf0e9\uf0e9\uf0e9\uf0e9'), (5, '\uf0e9\uf0e9\uf0e9\uf0e9\uf0e9')], default=5),
        ),
    ]
